## How to represent missing values and infinite?
#### Python solution of the survey

##### Python code #001:
```python
import numpy as np

# Create a 2D array (3x3 for example)
arr2d = np.array([[1, 2, 3],
                  [4, np.nan, 6],  # np.nan represents a missing value
                  [7, np.inf, 9]])  # np.inf represents an infinite value

print("Array with missing and infinite values:")
print(arr2d)


#### Output #001

```lua
Array with missing and infinite values:
[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7. inf  9.]]

## The Machinelearningplus solution of the survey

#### Python code #002:
```python
import numpy as np

# Create a 2D array (3x4 for example)
arr2 = np.array([[1, 2, 3, 4],
                 [3, 5, 6, 7],
                 [5, 6, 7, 8]])

# Insert a nan and an inf
arr2[1, 1] = np.nan  # not a number
arr2[1, 2] = np.inf  # infinite

# Output the modified array
print(arr2)


#### Output #002
```lua
# Insert a nan and an inf
arr2[1,1] = np.nan  # not a number
arr2[1,2] = np.inf  # infinite
arr2

#> array([[  1.,   2.,   3.,   4.],
#>        [  3.,  nan,  inf,   6.],
#>        [  5.,   6.,   7.,   8.]])

#### Python code #003:
```Python
import numpy as np

# Create a 2D array (3x4 for example)
arr2 = np.array([[1, 2, 3, 4],
                 [3, np.nan, np.inf, 6],
                 [5, 6, 7, 8]])

# Replace nan and inf with -1. Don't use arr2 == np.nan
missing_bool = np.isnan(arr2) | np.isinf(arr2)
arr2[missing_bool] = -1

# Output the modified array
print(arr2)


#### Output #003
```lua
# Replace nan and inf with -1. Don't use arr2 == np.nan
missing_bool = np.isnan(arr2) | np.isinf(arr2)
arr2[missing_bool] = -1  
arr2

#> array([[ 1.,  2.,  3.,  4.],
#>        [ 3., -1., -1.,  6.],
#>        [ 5.,  6.,  7.,  8.]])
